# Generated by Django 6.0.4 on 2026-07-02 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('investment', 'Investment')], default='expense', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='Date spent')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='expenses', to='money_app.expensetag')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='Date spent')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='incomes', to='money_app.incometag')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='Date spent')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='investments', to='money_app.investmenttag')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YearGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='expensetag',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_name'), name='money_app_expensetag_user_normalized_name_unique'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expense_user_date_index'),
        ),
        migrations.AddConstraint(
            model_name='incometag',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_name'), name='money_app_incometag_user_normalized_name_unique'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='income_user_date_index'),
        ),
        migrations.AddConstraint(
            model_name='investmenttag',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_name'), name='money_app_investmenttag_user_normalized_name_unique'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'date'], name='investment_user_date_index'),
        ),
        migrations.AlterUniqueTogether(
            name='yeargoal',
            unique_together={('user', 'year')},
        ),
    ]
