# Generated by Django 6.0 on 2025-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Date spent')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
