# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="expenses",
                to="money_app.category",
            ),
        ),
    ]
