# Generated by Django 6.0.4 on 2026-07-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
