# Generated by Django 6.0 on 2026-04-25 16:20

import django.db.models.deletion
from django.db import migrations, models


def copy_first_category_to_expense(apps, schema_editor):
    Expense = apps.get_model("money_app", "Expense")

    for expense in Expense.objects.order_by("id"):
        first_category = expense.categories.order_by("id").first()
        if first_category is not None:
            expense.category = first_category
            expense.save(update_fields=["category"])


def copy_category_back_to_m2m(apps, schema_editor):
    Expense = apps.get_model("money_app", "Expense")

    for expense in Expense.objects.exclude(category__isnull=True):
        expense.categories.add(expense.category)


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0002_category_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='money_app.category'),
        ),
        migrations.RunPython(copy_first_category_to_expense, copy_category_back_to_m2m),
        migrations.RemoveField(
            model_name='expense',
            name='categories',
        ),
    ]
