# Generated by Django 6.0 on 2026-04-25 17:30

import django.utils.timezone
from django.db import migrations, models


def delete_existing_expenses(apps, schema_editor):
    Expense = apps.get_model("money_app", "Expense")
    Expense.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0006_expense_user'),
    ]

    operations = [
        migrations.RunPython(delete_existing_expenses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='Date spent'),
        ),
    ]
