# Generated by Django 6.0.4 on 2026-06-15 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0009_yeargoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeargoal',
            old_name='user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='yeargoal',
            unique_together={('user', 'year')},
        ),
        migrations.AlterField(
            model_name='yeargoal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
